# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.task_controller_api import TaskControllerApi


class TestTaskControllerApi(unittest.TestCase):
    """TaskControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaskControllerApi()

    def tearDown(self) -> None:
        pass

    def test_create_task(self) -> None:
        """Test case for create_task

        """
        pass

    def test_delete_task(self) -> None:
        """Test case for delete_task

        """
        pass

    def test_disable_task_reminder(self) -> None:
        """Test case for disable_task_reminder

        """
        pass

    def test_enable_task_reminder(self) -> None:
        """Test case for enable_task_reminder

        """
        pass

    def test_get_all_tasks(self) -> None:
        """Test case for get_all_tasks

        """
        pass

    def test_get_task_by_id(self) -> None:
        """Test case for get_task_by_id

        """
        pass

    def test_get_task_statistics(self) -> None:
        """Test case for get_task_statistics

        """
        pass

    def test_get_tasks_by_completed(self) -> None:
        """Test case for get_tasks_by_completed

        """
        pass

    def test_get_tasks_by_date_range(self) -> None:
        """Test case for get_tasks_by_date_range

        """
        pass

    def test_get_tasks_by_location(self) -> None:
        """Test case for get_tasks_by_location

        """
        pass

    def test_mark_task_as_completed(self) -> None:
        """Test case for mark_task_as_completed

        """
        pass

    def test_mark_task_as_uncompleted(self) -> None:
        """Test case for mark_task_as_uncompleted

        """
        pass

    def test_search_tasks_by_title(self) -> None:
        """Test case for search_tasks_by_title

        """
        pass

    def test_toggle_task_completion(self) -> None:
        """Test case for toggle_task_completion

        """
        pass

    def test_update_task(self) -> None:
        """Test case for update_task

        """
        pass


if __name__ == '__main__':
    unittest.main()
